version: "3.9"

services:
  web:
    build: .
    container_name: smart-home-web
    command: bash -c "python manage.py migrate && gunicorn smart_home.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: smart-home-worker
    command: celery -A smart_home worker -l info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: smart-home-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-smart_home}
      POSTGRES_USER: ${POSTGRES_USER:-smart_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smart_pass}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: smart-home-redis
    ports:
      - "6379:6379"

volumes:
  db_data:
